### ISSUE TITLE
Functions declared with the naked attribute also require basic asm

### ISSUE THREAD

**Issue by ryanpatiency** [jserv/mini-arm-os#23]
https://github.com/jserv/mini-arm-os/blob/4437a6596e694aa6db83680923323a3bc53d8a37/07-Threads/threads.c#L29

According to gcc onlinedocs:https://gcc.gnu.org/onlinedocs/gcc/ARM-Function-Attributes.html

**Comment by jserv** [comment]
Can you send pull request to fix naked attribute usage?
